# version: "3.4"
services:
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
  web:
    build: .
    image: pi-air-quality-monitor
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
        - REDIS_HOST=redis
        - PORT=8000
    volumes:
      - ./src:/code
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - "redis"
    ports:
      - "8000:8000"
    restart: unless-stopped
